# Generated by Django 5.0.6 on 2024-06-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegulationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(choices=[('NATIONAL', 'National'), ('WESTERN_REGION', 'Western Region'), ('SOUTHERN_REGION', 'Southern Region'), ('EASTERN_REGION', 'Eastern Region'), ('NORTHERN_REGION', 'Northern Region')], default='NATIONAL', max_length=50)),
                ('contact_information', models.TextField()),
                ('regulatory_scope', models.TextField()),
                ('legal_documents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('compliance_guidelines', models.TextField()),
                ('industry_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulator.industrysector')),
                ('regulation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulator.regulationtype')),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulator.regulator')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulator.technology')),
            ],
        ),
    ]
