# Generated by Django 5.0.6 on 2024-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='compliance_guidelines',
            new_name='regulatorydetails',
        ),
        migrations.AlterField(
            model_name='regulator',
            name='jurisdiction',
            field=models.CharField(choices=[('National', 'National'), ('Scotland', 'Scotland'), ('England', 'England')], default='NATIONAL', max_length=50),
        ),
    ]
