# Generated by Django 5.0.6 on 2024-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0002_rename_compliance_guidelines_regulation_regulatorydetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='regulator',
        ),
        migrations.AddField(
            model_name='regulation',
            name='regulators',
            field=models.ManyToManyField(related_name='regulations', to='regulator.regulator'),
        ),
    ]
