# Generated by Django 5.0.6 on 2024-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0003_remove_regulation_regulator_regulation_regulators'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
