# Generated by Django 5.0.6 on 2024-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0004_regulation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulator',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='regulator',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulator',
            name='phone_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
