# Generated by Django 5.0.6 on 2024-08-12 14:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0006_regulation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='regulatorydetails',
            field=tinymce.models.HTMLField(),
        ),
    ]
